### ISSUE TITLE
OSError : [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by LAUBENicolas** [bellockk/alphashape#17]
* Alpha Shape Toolbox version: all versions
* Python version: 3.7
* Operating System: windows pro

### Description

After installing alphashape I get this error when I try to import alphashape:

Traceback (most recent call last):
  File "computer_vision/segmentation/concave_hull_segmentation.py", line 7, in <module>
    from alphashape import alphashape
File "C:\Users\nlb\Anaconda3\envs\ai_platform\lib\site-packages\alphashape\__init__.py", line 6, in <module>
    from .alphashape import alphashape
  File "C:\Users\nlb\Anaconda3\envs\ai_platform\lib\site-packages\alphashape\alphashape.py", line 8, in <module>
    from shapely.ops import cascaded_union, polygonize
  File "C:\Users\nlb\Anaconda3\envs\ai_platform\lib\site-packages\shapely\ops.py", line 13, in <module>
    from shapely.prepared import prep
  File "C:\Users\nlb\Anaconda3\envs\ai_platform\lib\site-packages\shapely\prepared.py", line 5, in <module>
    from shapely.geos import lgeos
  File "C:\Users\nlb\Anaconda3\envs\ai_platform\lib\site-packages\shapely\geos.py", line 154, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\nlb\Anaconda3\envs\ai_platform\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

### What I Did

```
from alphashape import alphashape, optimizealpha
points = [(0., 0.), (0., 1.), (1., 1.), (1., 0.), (0.5, 0.25), (0.5, 0.75), (0.25, 0.5), (0.75, 0.5)]
alpha = 0.95 * alphashape.optimizealpha(points)
hull = alphashape.alphashape(points, alpha)
```

**Comment by LAUBENicolas** [comment]
Using conda for the installation solved the problem.
(I forgot to use forge as mentionned in the docs)
